### ISSUE TITLE
Storybook utils don't keep types for inputs

### ISSUE THREAD

**Issue by guybenron** [wix/wix-ui#481] opened 2018-05-08 15:11 UTC
If a prop is of type number, the storybook displays a regular input box, which means that when a user inputs some other number the prop value is a string (even if it was initially a number).

This can have implications if the component is expecting a number prop but gets a string instead (calculations get screwed up).

The input should cast the type of the prop before sending it to the component or show an error.

**Comment by argshook** [comment] 2018-07-10 06:59
thanks, closing since duplicate of https://github.com/wix/wix-ui/issues/123

**Closed by argshook** 2018-07-10 06:59 UTC
Labels: bug, wix-storybook-utils
